<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-06T00:19:36Z" name="Sanity" finished-at="2021-08-06T00:19:59Z" duration-ms="23081">
    <groups>
      <group name="sanity">
        <method signature="TestCase2.CreateUser()[pri:-5, instance:batch_6_framework.TestCase2@1ff4931d]" name="CreateUser" class="batch_6_framework.TestCase2"/>
        <method signature="TestCase2.verifyLogin()[pri:-3, instance:batch_6_framework.TestCase2@1ff4931d]" name="verifyLogin" class="batch_6_framework.TestCase2"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2021-08-06T00:19:36Z" name="Test" finished-at="2021-08-06T00:19:59Z" duration-ms="23081">
      <class name="batch_6_framework.TestCase2">
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@1ff4931d]" started-at="2021-08-06T00:19:36Z" name="startTest" finished-at="2021-08-06T00:19:43Z" duration-ms="7278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="CreateUser()[pri:-5, instance:batch_6_framework.TestCase2@1ff4931d]" started-at="2021-08-06T00:19:43Z" name="CreateUser" finished-at="2021-08-06T00:19:44Z" duration-ms="411" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<invlaid creditial> but was:<invalid>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<invlaid creditial> but was:<invalid>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at batch_6_framework.TestCase2.CreateUser(TestCase2.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateUser -->
        <test-method is-config="true" signature="endTest()[pri:0, instance:batch_6_framework.TestCase2@1ff4931d]" started-at="2021-08-06T00:19:44Z" name="endTest" finished-at="2021-08-06T00:19:48Z" duration-ms="4155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method is-config="true" signature="startTest()[pri:0, instance:batch_6_framework.TestCase2@1ff4931d]" started-at="2021-08-06T00:19:48Z" name="startTest" finished-at="2021-08-06T00:19:54Z" duration-ms="6626" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="verifyLogin()[pri:-3, instance:batch_6_framework.TestCase2@1ff4931d]" started-at="2021-08-06T00:19:54Z" name="verifyLogin" finished-at="2021-08-06T00:19:55Z" duration-ms="381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="endTest()[pri:0, instance:batch_6_framework.TestCase2@1ff4931d]" started-at="2021-08-06T00:19:55Z" name="endTest" finished-at="2021-08-06T00:19:59Z" duration-ms="4208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- batch_6_framework.TestCase2 -->
    </test> <!-- Test -->
  </suite> <!-- Sanity -->
</testng-results>
